APP_PORT="9000"
GLUE_PUBLIC="true"

EMAIL_FROM="gluestack@demo"
EMAIL_WELCOME_TEMPLATE="welcome"

EMAIL_SENDER_HOST="smtp.mailtrap.io"
EMAIL_SENDER_PORT=2525
EMAIL_SENDER_AUTH_USER="44d9cc3fe2b277"
EMAIL_SENDER_AUTH_PASSWORD="dd99568af9a99c"

GLUE_APP_URL="%ENDPOINT_API%"
EMAIL_SERVICE_NAME="nodemailer"
EMAIL_SERVICE_ROUTE="send"

HASURA_GRAPHQL_URL="%GRAPHQL_GRAPHQL_URL%"
HASURA_ADMIN_SECRET="%GRAPHQL_HASURA_GRAPHQL_ADMIN_SECRET%"