table:
  name: users
  schema: public
insert_permissions:
  - role: user
    permission:
      check:
        id: X-HASURA-USER-ID
      set:
        id: X-HASURA-USER-ID
      columns: '*'
select_permissions:
  - role: user
    permission:
      columns: '*'
      filter:
        id: X-HASURA-USER-ID
      limit: 10
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns: '*'
      filter:
        id: X-HASURA-USER-ID
      check: null
      set:
        updated_at: NOW()
delete_permissions:
  - role: user
    permission:
      filter:
        id: X-HASURA-USER-ID
event_triggers:
  - name: users_trigger
    definition:
      enable_manual: false
      insert:
        columns: '*'
        payload: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{EVENT_BASE_URL}}'
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: false
      schedule: 0 0 * * *
      timeout: 60
