version: "3.9"
services:
  engine:
    container_name: engine
    restart: always
    build: /Users/shivamsinghal/Sites/projects/gluestack/apps/tutorial-apps/todo-app-storage/backend/engine
    volumes:
      - /Users/shivamsinghal/Sites/projects/gluestack/apps/tutorial-apps/todo-app-storage/backend/engine:/server
      - /server/node_modules
    env_file:
      - /Users/shivamsinghal/Sites/projects/gluestack/apps/tutorial-apps/todo-app-storage/backend/engine/.env
  graphql:
    container_name: graphql
    restart: always
    image: hasura/graphql-engine:v2.16.1
    ports:
      - 8080:8080
    volumes:
      - /Users/shivamsinghal/Sites/projects/gluestack/apps/tutorial-apps/todo-app-storage/backend/services/graphql:/hasura
    env_file:
      - /Users/shivamsinghal/Sites/projects/gluestack/apps/tutorial-apps/todo-app-storage/backend/services/graphql/.env
    healthcheck:
      test:
        - CMD-SHELL
        - timeout 1s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 5s
      timeout: 2s
      retries: 20
    depends_on:
      postgres:
        condition: service_healthy
  nginx:
    container_name: nginx
    restart: always
    build: /Users/shivamsinghal/Sites/projects/gluestack/apps/tutorial-apps/todo-app-storage/meta/router/nginx
    ports:
      - 10088:10088
    volumes:
      - /Users/shivamsinghal/Sites/projects/gluestack/apps/tutorial-apps/todo-app-storage/meta/router/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      graphql:
        condition: service_healthy
  storage:
    container_name: storage
    restart: always
    build: /Users/shivamsinghal/Sites/projects/gluestack/apps/tutorial-apps/todo-app-storage/backend/services/storage
    volumes:
      - /Users/shivamsinghal/Sites/projects/gluestack/apps/tutorial-apps/todo-app-storage/backend/services/storage:/server
      - /server/node_modules
    env_file:
      - /Users/shivamsinghal/Sites/projects/gluestack/apps/tutorial-apps/todo-app-storage/backend/services/storage/.env
  minio:
    container_name: minio
    restart: always
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 10310:9000
      - 9160:9001
    volumes:
      - /Users/shivamsinghal/Sites/projects/gluestack/apps/tutorial-apps/todo-app-storage/backend/storage/minio/data:/data
    environment:
      MINIO_ADMIN_END_POINT: host.docker.internal
      MINIO_CDN_END_POINT: 127.0.0.1
      MINIO_PORT: 10310
      MINIO_USE_SSL: false
      MINIO_ACCESS_KEY: gluestack
      MINIO_SECRET_KEY: password
      MINIO_PUBLIC_BUCKET: public
      MINIO_PRIVATE_BUCKET: private
  postgres:
    container_name: postgres
    restart: always
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - /Users/shivamsinghal/Sites/projects/gluestack/apps/tutorial-apps/todo-app-storage/backend/databases/postgres/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: todo_db_storage
    healthcheck:
      test:
        - CMD-SHELL
        - psql -U postgres -d todo_db_storage
      interval: 10s
      timeout: 10s
      retries: 50
      start_period: 30s
